# Generated by Django 5.0.3 on 2024-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentfname', models.CharField(max_length=50)),
                ('studentlname', models.CharField(max_length=50)),
                ('studentnumber', models.IntegerField()),
                ('studentemail', models.EmailField(max_length=254)),
                ('studentgender', models.CharField(max_length=50)),
                ('studentdob', models.IntegerField()),
                ('studentusername', models.CharField(max_length=50)),
                ('studentpassword', models.IntegerField()),
                ('studentaddress', models.CharField(max_length=50)),
                ('studentcourse', models.CharField(max_length=50)),
                ('studentimage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
